namespace: libredevops
name: zabbix
version: 2.3.1-a
readme: README.md
authors:
  - Dusan Matejka (@D3DeFi)
  - sky-joker (@sky-joker)
  - Werner Dijkerman (@dj-wasabi)
  - Troy Ward (@pyrodie18)
  - Evgeny Yurchenko (@BGmot)
  - vamgnu
  - santiagomr <s@santiagomr.com>
description: your collection description
license_file: LICENSE
tags:
  - monitoring
  - zabbix
repository: https://github.com/LibreDevOps/libredevops.zabbix.git
documentation: https://github.com/LibreDevOps/libredevops.zabbix.git
homepage: https://github.com/LibreDevOps/libredevops.zabbix
issues: https://github.com/LibreDevOps/libredevops.zabbix/issues
dependencies:
  ansible.windows: "*"
  ansible.netcommon: ">=3.1.1"
  ansible.posix: "*"
  community.general: "*"
  community.mysql: "*"
  community.postgresql: "*"
build_ignore: []

